###############################################
# Site infromation
###############################################
# ===================
# Basic information
# ===================
site_name: '星野 光 (Hikaru HOSHINO) - 兵庫県立大学'
site_author: 'Hikaru Hoshino'
copyright: Copyright &copy; 2020 Hikaru Hoshino
site_url: http://www.eng.u-hyogo.ac.jp/faculty/hoshino/ja/

# =======================
# Navigation Tree
# =======================
nav:
    - ホーム|Home: index.md
    - 自己紹介|CV: cv.md
    - 研究テーマ|Research: http://www.eng.u-hyogo.ac.jp/outline/faculty/hoshino/index.html
    - 研究成果リスト|Publications: publications.md
    - 教育活動|Education: education.md
    - 研究室配属|Message: laboratory.md

# =============================
# Other Settings (custom styleによる追加情報)
#
# keywords: サイトキーワード(サイトメタ情報)
# description: サイト紹介(サイトメタ情報)
# =============================
extra:
  keywords: 星野光, 星野 光, Hikaru Hoshino
  description: 星野 光 兵庫県立大学 助教
  side_menu_btn:
    - title: 研究室配属を考える方へ|message
      link:  /faculty/hoshino/ja/laboratory
    - title: 連絡先|contact
      link:  /faculty/hoshino/ja/schedule
  side_menu_under:
    - title: 計算機関連<br>(Python,LaTeXなど)
      link: /faculty/hoshino/pc/
  social:
    - icon: 'google'
      link: 'https://scholar.google.co.jp/citations?user=y3qOW84AAAAJ&hl=ja'
    - icon: 'github'
      link: 'https://github.com/hoshino06'
    - icon: 'linkedin'
      link: 'https://linkedin.com/in/hikaru-hoshino'


##########################################
# Configurations
###########################################
#-------------------------------
# site_dir 生成したサイトの出力先
#-------------------------------
site_dir: ../site/ja

#-------------------------
# mkdocsのテーマ設定
#-------------------------
theme:
  name: null
  custom_dir: '../custom_theme'
  highlightjs: true
  hljs_style: github
  hljs_languages:
    - tex
  language: 'ja'
  
plugins:
    - search

#--------------------------
# 外部のcss
#--------------------------
extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML'

google_analytics: ['UA-143840570-1', 'http://www.eng.u-hyogo.ac.jp']

#----------------------------------------
# Extensions for Python Markdown
# https://python-markdown.github.io/extensions
#
# attr_list: idやclassなどを追加可能({:id=xxx}や{:target=_blank}など)
# def_list:  dl,dtなどを設定する機能を追加
# markdown.extenxions.extra:  md_in_htmlを使用するため
#----------------------------------------
markdown_extensions:
  - footnotes
  - def_list
  - pymdownx.arithmatex
  - tables
  - attr_list
  - admonition
  - markdown.extensions.extra

